apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: {{ .Values.serviceB.replicaCount }}
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: {{ .Values.serviceB.image.repository }}:{{ .Values.serviceB.image.tag }}
          imagePullPolicy: {{ .Values.serviceB.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: SPRING_APPLICATION_NAME_B
            - name: SERVICEA_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: SERVICEA_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secret
                  key: SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
